source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-archives'
gem 'jemoji'
gem 'sass'
gem 'redcarpet'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'pygments.rb'
gem 'jekyll-lunr-js-search', :git => "https://github.com/InsidiousMind/jekyll-lunr-js-search.git"
