<!DOCTYPE html>
<html>
<head>
        
    <!--[if lt IE 9]>
    <script src="http://madlemmings.com/wp-content/themes/rise/js/html5/dist/html5shiv.js"></script>
    <script src="//css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    <!--[if IE 8]>
    <link rel="stylesheet" type="text/css" href="http://madlemmings.com/wp-content/themes/rise/css/ie8.css"/>
    <![endif]-->
    <!--[if IE 7]>
    <link rel="stylesheet" type="text/css" href="http://madlemmings.com/wp-content/themes/rise/css/ie7.css"/>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="UTF-8">
            <link rel="shortcut icon" href="http://madlemmings.com/wp-content/uploads/2015/08/madlemmings-favicon.ico"/>
    
    <link rel="stylesheet" href="http://madlemmings.com/wp-content/themes/rise-child/style.css" type="text/css" media="screen" title="no title"
          charset="utf-8"/>

            <meta name="google-site-verification" content="H6qr4XvMcI4EStji9QsCBG6i72U3fqAqjatuoWvg_-Y" />
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40004866-1', 'auto');
  ga('send', 'pageview');

</script>        <link rel="stylesheet" href="http://madlemmings.com/wp-content/themes/rise-child/style.css" type="text/css" media="screen" title="no title"
          charset="utf-8"/>
        <style type="text/css">.tve_more_tag {display: none !important}</style>
<!-- Open Graph Meta Tags & Twitter Card generated by Social Warfare V.1.3.13 http://warfareplugins.com -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@madlemmingz">
<meta name="twitter:title" content="Web Design, WordPress &#038; SEO – Zürich, Switzerland">
<meta name="twitter:description" content="WordPress Web Design and SEO Services - Zürich and Baden Switzerland. Helping businesses get more customers online using their websites.">
<meta name="twitter:site" content="@madlemmingz">
<script type="text/javascript">function parentIsEvil() { var html = null; try { var doc = top.location.pathname; } catch(err){ }; return(doc != "/wp-admin/customize.php"); }; if (top.location != self.location && parentIsEvil()) { top.location = self.location.href; };</script>
<!-- Open Graph Meta Tags & Twitter Card generated by Social Warfare V.1.3.13 http://warfareplugins.com -->


<!-- This site is optimized with the Yoast SEO plugin v2.3.5 - https://yoast.com/wordpress/plugins/seo/ -->
<title>Web Design, WordPress &#038; SEO – Zürich, Switzerland - Mad Lemmings</title>
<meta name="description" content="WordPress Web Design and SEO Services - Zürich and Baden Switzerland. Helping businesses get more customers online using their websites."/>
<link rel="canonical" href="http://madlemmings.com/" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Web Design, WordPress &#038; SEO – Zürich, Switzerland - Mad Lemmings" />
<meta property="og:description" content="WordPress Web Design and SEO Services - Zürich and Baden Switzerland. Helping businesses get more customers online using their websites." />
<meta property="og:url" content="http://madlemmings.com/" />
<meta property="og:site_name" content="Mad Lemmings" />
<meta property="og:image" content="http://madlemmings.com/wp-content/uploads/2015/04/web-design.png" />
<meta property="og:image" content="http://madlemmings.com/wp-content/uploads/2015/06/google-icon-round.png" />
<meta property="og:image" content="http://madlemmings.com/wp-content/uploads/2015/04/consulting.png" />
<script type='application/ld+json'>{"@context":"http:\/\/schema.org","@type":"WebSite","url":"http:\/\/madlemmings.com\/","name":"Mad Lemmings","potentialAction":{"@type":"SearchAction","target":"http:\/\/madlemmings.com\/?s={search_term_string}","query-input":"required name=search_term_string"}}</script>
<script type='application/ld+json'>{"@context":"http:\/\/schema.org","@type":"Organization","url":"http:\/\/madlemmings.com\/","sameAs":["https:\/\/www.facebook.com\/LemmingsMad","https:\/\/ch.linkedin.com\/in\/ashleyfaulkes","https:\/\/www.youtube.com\/user\/madlemmings","https:\/\/www.pinterest.com\/madlemmings\/","https:\/\/twitter.com\/madlemmingz"],"name":"Mad Lemmings","logo":"http:\/\/madlemmings.com\/wp-content\/uploads\/2015\/04\/madlemmings-logo.jpg"}</script>
<!-- / Yoast SEO plugin. -->

		<script type="text/javascript">
			window._wpemojiSettings = {"baseUrl":"http:\/\/s.w.org\/images\/core\/emoji\/72x72\/","ext":".png","source":{"concatemoji":"http:\/\/madlemmings.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.3.1"}};
			!function(a,b,c){function d(a){var c=b.createElement("canvas"),d=c.getContext&&c.getContext("2d");return d&&d.fillText?(d.textBaseline="top",d.font="600 32px Arial","flag"===a?(d.fillText(String.fromCharCode(55356,56812,55356,56807),0,0),c.toDataURL().length>3e3):(d.fillText(String.fromCharCode(55357,56835),0,0),0!==d.getImageData(16,16,1,1).data[0])):!1}function e(a){var c=b.createElement("script");c.src=a,c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var f,g;c.supports={simple:d("simple"),flag:d("flag")},c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.simple&&c.supports.flag||(g=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",g,!1),a.addEventListener("load",g,!1)):(a.attachEvent("onload",g),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),f=c.source||{},f.concatemoji?e(f.concatemoji):f.wpemoji&&f.twemoji&&(e(f.twemoji),e(f.wpemoji)))}(window,document,window._wpemojiSettings);
		</script>
		<style type="text/css">
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>
<link rel='stylesheet' id='wpr-flexslider-css'  href='http://madlemmings.com/wp-content/plugins/wp-reviews/css/flexslider.css?ver=4.3.1' type='text/css' media='all' />
<link rel='stylesheet' id='contact-form-7-css'  href='http://madlemmings.com/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=4.3' type='text/css' media='all' />
<link rel='stylesheet' id='social_warfare-css'  href='http://madlemmings.com/wp-content/plugins/social-warfare/css/style.css?ver=1.3.13' type='text/css' media='all' />
<link rel='stylesheet' id='toc-screen-css'  href='http://madlemmings.com/wp-content/plugins/table-of-contents-plus/screen.min.css?ver=1509' type='text/css' media='all' />
<link rel='stylesheet' id='tve_default-css'  href='http://madlemmings.com/wp-content/plugins/thrive-visual-editor/editor/css/thrive_default.css?ver=4.3.1' type='text/css' media='all' />
<link rel='stylesheet' id='tve_colors-css'  href='http://madlemmings.com/wp-content/plugins/thrive-visual-editor/editor/css/thrive_colors.css?ver=4.3.1' type='text/css' media='all' />
<link rel='stylesheet' id='tve_style_family_tve_flt-css'  href='http://madlemmings.com/wp-content/plugins/thrive-visual-editor/editor/css/thrive_flat.css?ver=1.101.13' type='text/css' media='all' />
<link rel='stylesheet' id='wpr-userrating-style-css'  href='http://madlemmings.com/wp-content/plugins/wp-reviews/css/user-rating/rating.css?ver=1.0' type='text/css' media='all' />
<link rel='stylesheet' id='wpr-colorbox-css'  href='http://madlemmings.com/wp-content/plugins/wp-reviews/css/colorbox/colorbox.css?ver=1.0' type='text/css' media='all' />
<link rel='stylesheet' id='jquery-ui-theme-css'  href='http://madlemmings.com/wp-content/plugins/wp-reviews/css/smoothness/jquery-ui-1.10.3.custom.min.css?v=1.0.0' type='text/css' media='all' />
<link rel='stylesheet' id='wpr-css'  href='http://madlemmings.com/wp-content/plugins/wp-reviews/css/style.css?ver=4.3.1' type='text/css' media='all' />
<link rel='stylesheet' id='wpr-bootstrap-css'  href='http://madlemmings.com/wp-content/plugins/wp-reviews/css/bootstrap.min.css?ver=4.3.1' type='text/css' media='all' />
<link rel='stylesheet' id='rise-style-css'  href='http://madlemmings.com/wp-content/themes/rise-child/style.css?ver=4.3.1' type='text/css' media='all' />
<link rel='stylesheet' id='thrive-reset-css'  href='http://madlemmings.com/wp-content/themes/rise/css/reset.css?v=1.0.0' type='text/css' media='all' />
<link rel='stylesheet' id='thrive-main-style-css'  href='http://madlemmings.com/wp-content/themes/rise/css/main_red.css?v=1.0.0' type='text/css' media='all' />
<link rel='stylesheet' id='font-awesome-styles-css'  href='http://madlemmings.com/wp-content/plugins/wp-reviews/inc/font-awesome/assets/css/font-awesome.min.css?ver=1.0' type='text/css' media='all' />
<!--[if lte IE 7]>
<link rel='stylesheet' id='font-awesome-ie7-css'  href='http://madlemmings.com/wp-content/plugins/wp-reviews/inc/font-awesome/assets/css/font-awesome-ie7.min.css?ver=1.0' type='text/css' media='all' />
<![endif]-->
<script type='text/javascript' src='http://madlemmings.com/wp-includes/js/jquery/jquery.js?v=1.0.0'></script>
<script type='text/javascript' src='http://madlemmings.com/wp-includes/js/jquery/jquery-migrate.min.js?v=1.0.0'></script>
<script type='text/javascript' src='http://madlemmings.com/wp-content/plugins/thrive-visual-editor/editor/js/compat.min.js?ver=1.101.13'></script>
<script type='text/javascript' src='http://madlemmings.com/wp-content/plugins/social-warfare/script.min.js?ver=1.3.13'></script>
<meta name="generator" content="WordPress 4.3.1" />
<link rel='shortlink' href='http://madlemmings.com/' />
<script type="text/javascript"><!--
function powerpress_pinw(pinw_url){window.open(pinw_url, 'PowerPressPlayer','toolbar=0,status=0,resizable=1,width=460,height=320');	return false;}
//-->
</script>
<script data-cfasync="false" src="//load.sumome.com/" data-sumo-site-id="6d0e302122217270e52951307c05600f300f15f450ff43f866a0c31e77c6cf29" async></script><style type="text/css">div#toc_container {width: 45%;}</style>        <style type="text/css">.wp-video-shortcode {
                max-width: 100% !important;
            }body { background:#FFF; }.cnt article h1 a { color:#333; }.bSe h1, h1.entry-title, h1.entry-title a { color:#333; }.bSe h2 { color:#464545; }.bSe h3 { color:#333; }.bSe h4 { color:#333; }.bSe h5 { color:#333; }.bSe h6 { color:#333; }.bSe p, .mry .awr-e p { color:#666; }.cnt .bSe { color:#666; }.cnt h1 a, .tve-woocommerce .bSe .awr .entry-title, .tve-woocommerce .bSe .awr .page-title{font-family:Roboto,sans-serif;}.bSe h1{font-family:Roboto,sans-serif;}.bSe h2,.tve-woocommerce .bSe h2{font-family:Roboto,sans-serif;}.bSe h3,.tve-woocommerce .bSe h3{font-family:Roboto,sans-serif;}.bSe h4{font-family:Roboto,sans-serif;}.bSe h5{font-family:Roboto,sans-serif;}.bSe h6{font-family:Roboto,sans-serif;}#text_logo{font-family:Roboto,sans-serif;}.cnt h1 a { font-weight:500; }.bSe h1 { font-weight:500; }.bSe h2 { font-weight:500; }.bSe h3 { font-weight:500; }.bSe h4 { font-weight:500; }.bSe h5 { font-weight:500; }.bSe h6 { font-weight:500; }.cnt{font-family:Roboto,sans-serif;font-weight:300;}article strong {font-weight: bold;}.cnt p, .tve-woocommerce .product p, .tve-woocommerce .products p{font-family:Roboto,sans-serif;font-weight:300;}article strong {font-weight: bold;}.bSe h1, .bSe .entry-title { font-size:46px; }.cnt { font-size:18px; }.thrivecb { font-size:18px; }.out { font-size:18px; }.aut p { font-size:18px; }.cnt p { line-height:1.5em; }.thrivecb { line-height:1.5em; }.bSe a, .cnt a { color:#6d161e; }.bSe .faq h4{font-family:Roboto,sans-serif;font-weight:300;}article strong {font-weight: bold;}header nav > ul.menu > li > a { color:#fff; }header nav > ul.menu > li >  a:hover { color:#fff; }header nav > ul > li.current_page_item > a:hover { color:#fff; }header nav > ul > li.current_menu_item > a:hover { color:#fff; }header nav > ul > li.current_menu_item > a:hover { color:#fff; }header nav > ul > li > a:active { color:#fff; }header #logo > a > img { max-width:200px; }header ul.menu > li.h-cta > a { color:#FFFFFF!important; }header ul.menu > li.h-cta > a { background:#e4cbc7; }header ul.menu > li.h-cta > a { border-color:#e4cbc7; }header ul.menu > li.h-cta > a:hover { color:#e4cbc7!important; }header ul.menu > li.h-cta > a:hover { background:transparent; }</style>
        
	<!-- This site is optimized with the WordPress Reviews Pro Plugin 1.1.9.7 by http://authorhreview.com -->

            <style type="text/css">footer .fmw{
   padding: 30px 0;
}
header.center{
   margin-bottom: 0;
}</style>
        
</head>
<body class="home page page-id-7465 page-template page-template-fullwidth-page page-template-fullwidth-page-php custom-background">





<div class="h-bi">
    <div id="floating_menu" data-float="float"
         data-social='0'>
        <header class="center"
                style="">
                        <div class="h-i">
                <div class="wrp">
                                                <div id="logo" >
                                <a href="http://madlemmings.com/"><img src="http://madlemmings.com/wp-content/uploads/2015/07/madlemmings-logo-new-60.png"></a>
                            </div>
                            <div class="header-banner"><h2>WordPress Websites That Get You Customers</h2></div>
                                                                        <div class="m-s">
                            <div class="hsm"></div>
                            <div class="m-si">
                                                                                                    <nav class="menu-main-container"><ul id="menu-main" class="menu"><li  id="menu-item-8193" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children toplvl dropdown"><a  href="http://madlemmings.com/services/">Services</a><ul class="sub-menu">	<li  id="menu-item-8152" class="menu-item menu-item-type-post_type menu-item-object-page"><a  class="colch"  href="http://madlemmings.com/website-design/">Website Design</a></li>
	<li  id="menu-item-9353" class="menu-item menu-item-type-post_type menu-item-object-page"><a  class="colch"  href="http://madlemmings.com/portfolio-clients/">Portfolio</a></li>
	<li  id="menu-item-7147" class="menu-item menu-item-type-post_type menu-item-object-page"><a  class="colch"  href="http://madlemmings.com/client-work/">Testimonials</a></li>
	<li  id="menu-item-7297" class="menu-item menu-item-type-post_type menu-item-object-page"><a  class="colch"  href="http://madlemmings.com/seo-from-mad-lemmings/">SEO</a></li>
	<li  id="menu-item-9505" class="menu-item menu-item-type-post_type menu-item-object-page"><a  class="colch"  href="http://madlemmings.com/frequently-asked-questions/">Frequently Asked Questions</a></li>
</ul></li>
<li  id="menu-item-4272" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children toplvl dropdown"><a  href="http://madlemmings.com/blog/">Blog</a><ul class="sub-menu">	<li  id="menu-item-5220" class="menu-item menu-item-type-taxonomy menu-item-object-category"><a  class="colch"  href="http://madlemmings.com/category/wordpress/">WordPress</a></li>
	<li  id="menu-item-8051" class="menu-item menu-item-type-taxonomy menu-item-object-category"><a  class="colch"  href="http://madlemmings.com/category/seo/">SEO</a></li>
	<li  id="menu-item-5219" class="menu-item menu-item-type-taxonomy menu-item-object-category"><a  class="colch"  href="http://madlemmings.com/category/blogging/">Blogging</a></li>
	<li  id="menu-item-5218" class="menu-item menu-item-type-taxonomy menu-item-object-category"><a  class="colch"  href="http://madlemmings.com/category/social-media/">Social Media</a></li>
	<li  id="menu-item-4309" class="menu-item menu-item-type-post_type menu-item-object-page"><a  class="colch"  href="http://madlemmings.com/guest-posting/">Guest Post</a></li>
</ul></li>
<li  id="menu-item-1871" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children toplvl dropdown"><a  href="http://madlemmings.com/useful-tools/">Tools &#038; Resources</a><ul class="sub-menu">	<li  id="menu-item-3791" class="menu-item menu-item-type-post_type menu-item-object-page"><a  class="colch"  href="http://madlemmings.com/how-start-wordpress-website-blog/">Start A Website</a></li>
	<li  id="menu-item-9849" class="menu-item menu-item-type-post_type menu-item-object-page"><a  class="colch"  href="http://madlemmings.com/divi-theme-example-websites/">Divi Theme Example Websites</a></li>
	<li  id="menu-item-9920" class="menu-item menu-item-type-post_type menu-item-object-page"><a  class="colch"  href="http://madlemmings.com/elegant-theme-shortcodes-explained/">Elegant Theme Shortcodes</a></li>
</ul></li>
<li  id="menu-item-23" class="menu-item menu-item-type-post_type menu-item-object-page toplvl"><a  href="http://madlemmings.com/about/">About</a></li>
<li  id="menu-item-34" class="menu-item menu-item-type-post_type menu-item-object-page toplvl"><a  href="http://madlemmings.com/contact/">Contact</a></li>
</ul></nav>                                                                    
                                                            </div>
                        </div>
                    
                </div>
            </div>

        </header>
    </div>
</div>





            
        
        <div class="wrp cnt">


            <section class="bSe fullWidth">
                
<div class="awr">

    
    
    
            
    
    
        <div class="awr-i">
        <div id="tve_flt" class="tve_flt"><div id="tve_editor" class="tve_shortcode_editor"><div class="thrv_wrapper thrv_page_section" data-tve-style="1" style="margin-top: -30px !important;" id="hero-section">
<div class="pswr out" style="background-color: #EAEAEA">
<div class="in darkSec pddbg" data-width="2000" data-height="500" style="box-sizing: border-box; max-width: 1951px; box-shadow: none; background-image: url(http://madlemmings.com/wp-content/uploads/2015/08/happy-plugins.jpg);">
<div class="cck tve_clearfix">
<div class="thrv_wrapper thrv_columns">
<div class="tve_colm tve_twc"></div>
<div class="tve_colm tve_twc tve_lst"><p data-default="Enter your text here..." class="bold_text tve_p_center rft" style="color: rgb(255, 35, 35); line-height: 49px; font-size: 44px;" data-unit="px"><span class="tve_custom_font_size rft" style="font-size: 44px;"><b>NO IDEA WHAT WORDPRESS PLUGINS YOU NEED?</b></span></p><p data-default="Enter your text here..." class="bold_text tve_p_center" style="font-size: 24px; color: rgb(93, 93, 93); margin-left: 0px !important; margin-bottom: 20px !important;"><span class="bold_text"><span class="tve_custom_font_size  rft" style="font-size: 36px;">Why Not Make Your Life Easy?</span></span></p><p class="bold_text tve_p_center" style="font-size: 24px; color: rgb(21, 21, 21); margin-left: 0px !important; margin-bottom: 75px !important;"><span class="tve_custom_font_size  rft bold_text" style="font-size: 32px;"><font color="#5d5d5d">Grab My﻿ </font><font color="#ff4545">Best WordPress Plugins List</font></span><font color="#e60e0e"></font></p><div class="thrv_wrapper thrv_button_shortcode tve_centerBtn tve_ea_thrive_lightbox" data-tve-style="1">
<div class="tve_btn tve_nb tve_bigBtn tve_btn6 tve_orange">
<a href="" class="tve_btnLink tve_evt_manager_listen tve_et_click" style="font-size: 29px; line-height: 29px; padding-top: 26px !important; padding-bottom: 26px !important;" data-tcb-events="__TCB_EVENT_[{&quot;t&quot;:&quot;click&quot;,&quot;a&quot;:&quot;thrive_lightbox&quot;,&quot;config&quot;:{&quot;l_id&quot;:&quot;8870&quot;,&quot;l_anim&quot;:&quot;instant&quot;}}]_TNEVE_BCT__">
<span class="tve_left tve_btn_im">
<i class="tve_sc_icon icon-mail" data-tve-icon="icon-mail" style="background-image: none;"></i>
<span class="tve_btn_divider"></span>
</span>
<span class="tve_btn_txt">SEND ME THE LIST</span>
</a>
</div>
</div></div>
</div>
</div>
</div>
</div>
</div><p data-default="Enter your text here..." class="tve_p_center" style="margin-bottom: 5px !important; margin-top: 80px !important; line-height: 29px;" data-unit="px"><span class="tve_custom_font_size  rft" style="font-size: 36px;"><b><span class="tve_custom_font_size  rft" style="font-size: 46px;">Why Not Have A WordPress Website </span></b></span></p><p class="tve_p_center" style="line-height: 29px; margin-bottom: 50px !important; margin-top: 0px !important;"><span class="tve_custom_font_size  rft" style="font-size: 36px;"><b><span class="tve_custom_font_size  rft" style="font-size: 46px;">That Gets You More Customers?</span></b></span></p><div class="thrv_wrapper thrv_columns tve_clearfix  div-pink" style="padding: 30px 20px !important; margin-top: 0px !important; border-top: 2px solid #ff4545;">
<div class="tve_colm tve_oth"><div style="width: 184px;" class="thrv_wrapper tve_image_caption aligncenter">
<span class="tve_image_frame">
<a href="http://madlemmings.com/website-design-blog-customization/" target="_self" rel=""><img class="tve_image" alt="" src="http://madlemmings.com/wp-content/uploads/2015/04/web-design.png" style="width: 184px;" data-jpibfi-indexer="1"></a>
</span>
</div><div class="thrv_wrapper thrv_content_container_shortcode">
<div class="tve_clear"></div>
<div class="tve_content_inner tve_center" style="width: 300px; min-width: 50px; min-height: 2em;">
<p class="tve_p_center  rft" style="font-size: 36px; color: rgb(93, 93, 93);"><span class="tve_custom_font_size" style="font-size: 26px;"><b>WordPress Web Design</b></span></p><p data-default="Enter your text here..." class="tve_p_center">Whether it's a new website on a budget or a complete custom rebuild, we can help you stand out online and win more customers.</p><p data-default="Enter your text here..." class="tve_p_center">Choose from one of our proven website designs, or get a custom one to suit your business needs.</p><div class="thrv_wrapper thrv_button_shortcode tve_centerBtn" data-tve-style="1">
<div class="tve_btn tve_nb tve_black tve_btn3 tve_smallBtn" data-tve-custom-colour="38905444" style="margin-top: 25px !important;">
<a href="http://madlemmings.com/website-design/" class="tve_btnLink" style="font-size: 15px; line-height: 15px;" target="_blank" rel="nofollow">
<span class="tve_left tve_btn_im">
<i></i>
<span class="tve_btn_divider"></span>
</span>
<span class="tve_btn_txt">Learn More</span>
</a>
</div>
</div>
</div>
<div class="tve_clear"></div>
</div></div>
<div class="tve_colm tve_oth tve_clearfix"><div style="width: 184px; padding: 0px 10px;" class="thrv_wrapper tve_image_caption aligncenter">
<span class="tve_image_frame">
<a href="http://madlemmings.com/seo-from-mad-lemmings/" target="_self" rel=""><img class="tve_image" alt="" src="http://madlemmings.com/wp-content/uploads/2015/06/google-icon-round.png" style="width: 184px;" data-jpibfi-indexer="1"></a>
</span>
</div><div class="thrv_wrapper thrv_content_container_shortcode">
<div class="tve_clear"></div>
<div class="tve_content_inner tve_center" style="width: 300px; min-width: 50px; min-height: 2em;">
<p class="tve_p_center  rft" style="font-size: 36px; color: rgb(93, 93, 93);"><span class="tve_custom_font_size" style="font-size: 26px;"><b>SEO Services</b></span></p><p data-default="Enter your text here..." class="tve_p_center">Stuck on the 10th page of Google?&nbsp;​ Let us help you:</p><ul class="thrv_wrapper" style="margin-bottom: 0px !important;"><li class="">Find the right keywords for your business to help get more customers</li><li class="">Fix your website so it can rank naturally</li></ul><div class="thrv_wrapper thrv_button_shortcode tve_centerBtn" data-tve-style="1">
<div class="tve_btn tve_nb tve_black tve_btn3 tve_smallBtn" data-tve-custom-colour="74701348" style="margin-top: 10px !important;">
<a href="http://madlemmings.com/seo-from-mad-lemmings/" class="tve_btnLink" style="font-size: 15px; line-height: 15px;">
<span class="tve_left tve_btn_im">
<i></i>
<span class="tve_btn_divider"></span>
</span>
<span class="tve_btn_txt">Learn More</span>
</a>
</div>
</div>
</div>
<div class="tve_clear"></div>
</div></div>
<div class="tve_colm tve_thc tve_lst"><div style="width: 184px;" class="thrv_wrapper tve_image_caption aligncenter">
<span class="tve_image_frame">
<img class="tve_image" alt="" src="http://madlemmings.com/wp-content/uploads/2015/04/consulting.png" style="width: 184px;" data-jpibfi-indexer="1">
</span>
</div><div class="thrv_wrapper thrv_content_container_shortcode">
<div class="tve_clear"></div>
<div class="tve_content_inner tve_center" style="width: 300px; min-width: 50px; min-height: 2em;">
<p class="tve_p_center  rft" style="font-size: 36px;"><span class="tve_custom_font_size" style="font-size: 26px;"><b>Coaching &amp; Consulting</b></span></p><p data-default="Enter your text here..." class="tve_p_center">Not sure how to move forward with your website or blog? No idea how to improve your rankings on Google? </p><p class="tve_p_center">We can help you plan and take the next steps to move your business forward</p><div class="thrv_wrapper thrv_button_shortcode tve_centerBtn" data-tve-style="1">
<div class="tve_btn tve_nb tve_black tve_btn3 tve_smallBtn" data-tve-custom-colour="15015331" style="margin-top: 50px !important;">
<a href="http://madlemmings.com/seo-from-mad-lemmings/" class="tve_btnLink" style="font-size: 15px; line-height: 15px;">
<span class="tve_left tve_btn_im">
<i></i>
<span class="tve_btn_divider"></span>
</span>
<span class="tve_btn_txt">Learn More</span>
</a>
</div>
</div>
</div>
<div class="tve_clear"></div>
</div></div>
</div><div class="thrv_wrapper">
<hr class="tve_sep tve_sep1">
</div><div class="thrv_wrapper thrv_content_container_shortcode">
<div class="tve_clear"></div>
<div class="tve_content_inner tve_center" style="width: 1188px; min-width: 50px; min-height: 2em;">
<p data-default="Enter your text here..." class="tve_p_center" style="margin-bottom: 50px !important; margin-top: 80px !important;"><span class="tve_custom_font_size  rft" style="font-size: 36px;"><b><span class="tve_custom_font_size  rft" style="font-size: 46px;">The Latest Blog Posts</span></b></span></p><div class="thrv_wrapper thrv_post_grid">
<div class="thrive-shortcode-config" style="display: none !important"></div>        
    
    <div class="tve_post_grid_wrapper tve_clearfix tve_post_grid_grid">
                                                            <div class="tve_pg_row tve_clearfix">
                            <div class="tve_post tve_post_width_2 tve_first">
                    <div class="tve_pg_container" >
                                                                                                                            <a href="http://madlemmings.com/2015/11/11/visual-content-boost-traffic/">
            <div class="tve_post_grid_image_wrapper"
                 style="background-image: url('http://madlemmings.com/wp-content/uploads/2015/11/visual-content-boost-traffic.jpg'); height: 170px">
                <div class="tve_pg_img_overlay">
                    <span class="thrv-icon thrv-icon-forward"></span>
                </div>
            </div>
        </a>
                                                                                                                                                        <span class="tve-post-grid-title "
                style="font-size: 30px;"><a             href="http://madlemmings.com/2015/11/11/visual-content-boost-traffic/">How to use visual content to boost your traffic #contentmarketing</a></span>                                                                                                                                                        <div class="tve-post-grid-text"
             style="border-top-width: 1px;" >Every day, bloggers and companies alike are producing tons of new content. So it's only natural that your blog or website&#91;...&#93;</div>                                                                                                                <div class="tve_pg_more">
            <a href="http://madlemmings.com/2015/11/11/visual-content-boost-traffic/">Read More</a>
            <span class="thrv-icon thrv-icon-uniE602"></span>
        </div>
                                                    </div>
                </div>
                                                            <div class="tve_post tve_post_width_2 tve_last">
                    <div class="tve_pg_container" >
                                                                                                                            <a href="http://madlemmings.com/2015/11/03/grammarly-review/">
            <div class="tve_post_grid_image_wrapper"
                 style="background-image: url('http://madlemmings.com/wp-content/uploads/2015/10/Grammarly.jpg'); height: 170px">
                <div class="tve_pg_img_overlay">
                    <span class="thrv-icon thrv-icon-forward"></span>
                </div>
            </div>
        </a>
                                                                                                                                                        <span class="tve-post-grid-title "
                style="font-size: 30px;"><a             href="http://madlemmings.com/2015/11/03/grammarly-review/">Grammarly: Is it a must for content creators? [Review]</a></span>                                                                                                                                                                                                                                                                <div class="tve_pg_more">
            <a href="http://madlemmings.com/2015/11/03/grammarly-review/">Read More</a>
            <span class="thrv-icon thrv-icon-uniE602"></span>
        </div>
                                                    </div>
                </div>
                            </div>
                                                            <div class="tve_pg_row tve_clearfix">
                            <div class="tve_post tve_post_width_2 tve_first">
                    <div class="tve_pg_container" >
                                                                                                                            <a href="http://madlemmings.com/2015/10/27/website-design-conversion-rate/">
            <div class="tve_post_grid_image_wrapper"
                 style="background-image: url('http://madlemmings.com/wp-content/uploads/2015/10/web-design-increase-conversion.jpg'); height: 170px">
                <div class="tve_pg_img_overlay">
                    <span class="thrv-icon thrv-icon-forward"></span>
                </div>
            </div>
        </a>
                                                                                                                                                        <span class="tve-post-grid-title "
                style="font-size: 30px;"><a             href="http://madlemmings.com/2015/10/27/website-design-conversion-rate/">4 Ways Great Web Design Can Help You Sell More Bananas</a></span>                                                                                                                                                        <div class="tve-post-grid-text"
             style="border-top-width: 1px;" >As a website site owner or blogger, I am sure you are constantly searching for ways to increase your conversions and sales. This&#91;...&#93;</div>                                                                                                                <div class="tve_pg_more">
            <a href="http://madlemmings.com/2015/10/27/website-design-conversion-rate/">Read More</a>
            <span class="thrv-icon thrv-icon-uniE602"></span>
        </div>
                                                    </div>
                </div>
                                                            <div class="tve_post tve_post_width_2 tve_last">
                    <div class="tve_pg_container" >
                                                                                                                            <a href="http://madlemmings.com/2015/10/22/2015-searchlove-seo-conference-london/">
            <div class="tve_post_grid_image_wrapper"
                 style="background-image: url('http://madlemmings.com/wp-content/uploads/2015/10/searchlove-seo-conference-london1.jpg'); height: 170px">
                <div class="tve_pg_img_overlay">
                    <span class="thrv-icon thrv-icon-forward"></span>
                </div>
            </div>
        </a>
                                                                                                                                                        <span class="tve-post-grid-title "
                style="font-size: 30px;"><a             href="http://madlemmings.com/2015/10/22/2015-searchlove-seo-conference-london/">SearchLove: How This #SEO Conference in London Almost Melted My Brain</a></span>                                                                                                                                                        <div class="tve-post-grid-text"
             style="border-top-width: 1px;" >SearchLove. Yup, it is a real conference, focused on SEO and run by the amazing Distilled, an online marketing agency&#91;...&#93;</div>                                                                                                                <div class="tve_pg_more">
            <a href="http://madlemmings.com/2015/10/22/2015-searchlove-seo-conference-london/">Read More</a>
            <span class="thrv-icon thrv-icon-uniE602"></span>
        </div>
                                                    </div>
                </div>
                            </div>
                                            </div>
    

</div>
</div>
<div class="tve_clear"></div>
</div></div></div>    </div>

    
    
        </div>

            </section>


        </div>
        <div class="clear"></div>
    


<footer>
                <div class="fmw">
            <div class="wrp">
                                    <div class="colm oth ">
                        
        <section class="wat" id="widget_thrive_text-2">
            <div class="scn">
                                    <p class="ttl">Contact Me</p>
                                <p>Mad Lemmings GmbH<br />
Muellernstrasse 30<br />
Wettingen 5430<br />
Switzerland<br />
+41 77 486 7508</p>
<p>ashley@madlemmings.com</p>
                <div class="clear"></div>
            </div>
        </section>
                        </div>
                                    <div class="colm oth ">
                        <section id="text-18" class="col"><div class="scn"><p class="ttl">Important Links</p>			<div class="textwidget"><a href="http://madlemmings.com/affiliate-disclosure/"> Affiliate disclosure</a><br>
<a href="http://madlemmings.com/privacy-policy/"> Privacy Policy</a></div>
		</div></section>
        <section class="widget follow_me" id="widget_thrive_follow-2">
            <div class="scn">
                <div class="side_body">
                                            <p class="ttl">Follow Me On Social Media</p>
                                        <ul>
                        
                            <li class="sm_icons">
                                                                    <div class="bubb">
                                        <div class="bubble">
                                                                <div id="container-follow-twitter">
                        <a href="http://twitter.com/madlemmingz" class="twitter-follow-button"
                           data-show-count="false">Follow @madlemmingz</a>
                    </div>
                    <script>jQuery(window).load(function () {
                            ThriveApp.load_script("twitter");
                        });</script>
                                                            </div>
                                    </div>
                                                                <a href="javascript:void(0)"
                                   class="sm tw sm-1col" rel="twitter">
                                    <span></span>
                                </a>
                            </li>

                        
                            <li class="sm_icons">
                                                                    <div class="bubb">
                                        <div class="bubble">
                                                                <div id="container-follow-gprofile">
                        <div class="g-person" data-width="273" data-href="https://plus.google.com/u/4/+AshleyFaulkes/posts" data-layout="landscape" data-rel="author"
                             id="follow_me_content_gprofile"></div>
                    </div>
                                                            </div>
                                    </div>
                                                                <a href="javascript:void(0)"
                                   class="sm gg sm-1col" rel="gprofile">
                                    <span></span>
                                </a>
                            </li>

                        
                            <li class="sm_icons">
                                                                    <div class="bubb">
                                        <div class="bubble">
                                                                <div id="container-follow-gpage">
                        <div class='g-follow' data-width="273" data-href="https://plus.google.com/+MadlemmingsMarketing/posts" data-layout="landscape" data-rel="author"
                             id="follow_me_content_gprofile"></div>
                    </div>

                                                            </div>
                                    </div>
                                                                <a href="javascript:void(0)"
                                   class="sm gg sm-1col" rel="gpage">
                                    <span></span>
                                </a>
                            </li>

                        
                            <li class="sm_icons">
                                                                    <div class="bubb">
                                        <div class="bubble">
                                                                <div id="container-follow-linkedin">
                        <script>
                            jQuery(window).load(function () {
                                ThriveApp.load_script("linkedin");
                            });
                        </script>
                        <script type='IN/MemberProfile' data-format='inline' data-id='https://ch.linkedin.com/in/ashleyfaulkes'></script>                    </div>
                                                            </div>
                                    </div>
                                                                <a href="javascript:void(0)"
                                   class="sm lk sm-1col" rel="linkedin">
                                    <span></span>
                                </a>
                            </li>

                        
                            <li class="sm_icons">
                                                                    <div class="bubb">
                                        <div class="bubble">
                                                                <div id="container-follow-pinterest">
                        <a data-pin-do="buttonFollow"
                           href="//www.pinterest.com/madlemmings/">http://pinterest.com/madlemmings</a>
                        <script>
                            jQuery(window).load(function () {
                                ThriveApp.load_script("pinterest");
                            });
                        </script>
                    </div>
                                                            </div>
                                    </div>
                                                                <a href="javascript:void(0)"
                                   class="sm pt sm-2col" rel="pinterest">
                                    <span></span>
                                </a>
                            </li>

                                            </ul>
                    <div class="clear"></div>
                </div>
            </div>

                            <script>jQuery(window).load(function () {
                        ThriveApp.load_script("google");
                    });</script>
            
        </section>
                            </div>
                                    <div class="colm oth lst">
                        <section id="text-16" class="col"><div class="scn"><p class="ttl">Powering Mad Lemmings</p>			<div class="textwidget"><h5>Theme: <a href="http://madlemmings.com/goto/thrive-themes-rise/">Rise by Thrive Themes</a></h5>
<h5>Hosting: <a href="http://madlemmings.com/goto/traffic-planet/">Traffic Planet (insanely fast)</a></h5>
<h5>Plugins: <a href="http://madlemmings.com/goto/thrive-leads/">Thrive Leads (popups etc)</a></h5>
<h5><a href="http://madlemmings.com/goto/social-warfare/">Social Media Buttons</a></h5></div>
		</div></section>                    </div>
                                <div class="clear"></div>
            </div>
        </div>
        <div class="fmm">
        <div class="wrp">
            <div class="ft-m">
                            </div>
        </div>
        <div class="wrp">
            <div class="ft-c">
                <p>
                                            Copyright 2015 © Mad Lemmings.                                                         </p>
            </div>
            <div class="ft-s">
                <ul>
                                                                                                                                                <li class="pt">
                            <a href="http://pinterest.com/madlemmings" target="_blank"></a>
                        </li>
                                    </ul>
                                    <span>Connect With Me:</span>
                            </div>
        </div>
        <div class="clear"></div>
    </div>
    </footer>


<script type="text/javascript"> var sw_cache_url = "http://madlemmings.com/" </script><div id="tve_notification_box"></div><link rel='stylesheet' id='thrive_events-css'  href='http://madlemmings.com/wp-content/plugins/thrive-visual-editor/editor/css/events.css?ver=1.101.13' type='text/css' media='all' />
<link rel='stylesheet' id='thrive_icon_pack-css'  href='//madlemmings.com/wp-content/uploads/2015/03/icomoon-2/style.css?ver=7.21' type='text/css' media='all' />
<script type='text/javascript' src='http://madlemmings.com/wp-content/plugins/contact-form-7/includes/js/jquery.form.min.js?v=1.0.0'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var _wpcf7 = {"loaderUrl":"http:\/\/madlemmings.com\/wp-content\/plugins\/contact-form-7\/images\/ajax-loader.gif","sending":"Sending ...","cached":"1"};
/* ]]> */
</script>
<script type='text/javascript' src='http://madlemmings.com/wp-content/plugins/contact-form-7/includes/js/scripts.js?ver=4.3'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var tocplus = {"visibility_show":"show","visibility_hide":"hide","width":"45%"};
/* ]]> */
</script>
<script type='text/javascript' src='http://madlemmings.com/wp-content/plugins/table-of-contents-plus/front.min.js?ver=1509'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var tve_frontend_options = {"ajaxurl":"http:\/\/madlemmings.com\/wp-admin\/admin-ajax.php","is_editor_page":"","page_events":[],"is_single":"1","social_fb_app_id":""};
/* ]]> */
</script>
<script type='text/javascript' src='http://madlemmings.com/wp-content/plugins/thrive-visual-editor/editor/js/thrive_content_builder_frontend.min.js?ver=1.101.13'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var ThriveApp = {"ajax_url":"http:\/\/madlemmings.com\/wp-admin\/admin-ajax.php","is_singular":"1","post_type":"page","lazy_load_comments":"1","comments_loaded":"0","theme_uri":"http:\/\/madlemmings.com\/wp-content\/themes\/rise"};
/* ]]> */
</script>
<script type='text/javascript' src='http://madlemmings.com/wp-content/themes/rise/js/script.js?v=1.0.0'></script>
<script type="text/javascript">var TVE_Event_Manager_Registered_Callbacks = TVE_Event_Manager_Registered_Callbacks || {};TVE_Event_Manager_Registered_Callbacks.thrive_lightbox = function(t,a,c){var $t=jQuery("#tve_thrive_lightbox_"+c.l_id).css("display", ""),a=c.l_anim?c.l_anim:"instant";TCB_Front.openLightbox($t,a);return false;};;</script><style type="text/css" class="tve_custom_style">[data-tve-custom-colour="7450991"]:hover { border-color: rgb(153, 153, 153) !important; background-color: rgb(255, 168, 76) !important; }
[data-tve-custom-colour="7450991"] { color: rgb(255, 255, 255) !important; text-shadow: rgb(255, 69, 69) 0px 1px 0px !important; box-shadow: transparent 0px 3px 3px 1px !important; border-color: rgb(153, 153, 153) !important; background-color: rgb(239, 151, 0) !important; }</style><div style="display: none" id="tve_thrive_lightbox_8870"><div class="tve_p_lb_overlay" data-style="opacity:0.800000011920929" style="opacity:0.800000011920929"></div><div class="tve_p_lb_content bSe cnt tcb-lp-lb" style="max-width:690px"><div class="tve_p_lb_inner" id="tve-p-scroller" style=""><article><div id="tve_flt" class="tve_flt"><div id="tve_editor" class="tve_shortcode_editor"><p data-default="Enter your text here..." class="rft tve_p_center bold_text" style="font-size: 40px; line-height: 50px; color: rgb(255, 10, 10);" data-unit="px"><span class="tve_custom_font_size rft bold_text" style="font-size: 40px;">Stop Wasting Hours Looking For WordPress Plugins!</span></p><p data-default="Enter your text here..." class="tve_p_center rft" style="margin-bottom: 5px !important; font-size: 32px;"><b><span class="tve_custom_font_size  rft" style="font-size: 34px;">Enter Your Details and Get the Plugins List</span> </b></p><p class="tve_p_center" style="font-size: 24px;">(and even more plugin goodness)</p><div class="thrv_wrapper thrv_lead_generation tve_clearfix tve_red tve_6 thrv_lead_generation_vertical" data-tve-style="1" data-tve-version="1" data-inputs-count="6" data-connection="api">
<input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Please enter a valid email address&quot;,&quot;phone&quot;:&quot;Please enter a valid phone number&quot;,&quot;required&quot;:&quot;Highlighted fields are required&quot;}">
<div class="thrv_lead_generation_code" style="display: none;"></div>
<div class="thrv_lead_generation_container tve_clearfix"><form method="post" action="#"><div class="tve_lead_generated_inputs_container tve_clearfix"><div class="tve_lead_fields_overlay"></div><div class="tve_lg_input_container tve_lg_input tve_lg_3"><input type="text" data-field="name" data-required="1" data-validation="none" name="name" placeholder="Name" data-placeholder="Name" style="padding-right: 10px;"></div><div class="tve_lg_input_container tve_lg_input tve_lg_3"><input type="text" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email" style="padding-right: 10px;"></div><input id="__tcb_lg_fc" type="hidden" name="__tcb_lg_fc" value="YToxOntzOjE0OiJhY3RpdmVjYW1wYWlnbiI7czoxOiIxIjt9"><input id="_back_url" type="hidden" name="_back_url" value="http:///wordpress-sign-up-download/"><input id="_submit_option" type="hidden" name="_submit_option" value="redirect"><div style="display: none"></div><div class="tve_lg_input_container tve_submit_container tve_lg_submit tve_lg_3" tve-data-style="1">
<button type="Submit" data-tve-custom-colour="7450991">Send Me The List</button>
</div></div></form></div>
</div></div></div></article></div><a href="javascript:void(0)" class="tve_p_lb_close" style="" title="Close">x</a></div></div></body>
</html>
<!-- Performance optimized by W3 Total Cache. Learn more: http://www.w3-edge.com/wordpress-plugins/

Page Caching using disk: enhanced

 Served from: madlemmings.com @ 2015-11-11 19:04:40 by W3 Total Cache -->